# Generated by Django 4.0.4 on 2022-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_headline_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='already_replied',
            field=models.BooleanField(default=False),
        ),
    ]
